### PR TITLE
Update MainActivity.java

### PR DESCRIPTION
**Pull request by xxmbaobao**

### CODE REVIEW

**Comment by xxmbaobao** [comment]
this Change easy to read

**Comment by nshmura** [comment]
Hi @xxmbaobao
This project uses Square's code style. So the method annotation is not wrapped.
https://github.com/square/java-code-styles

**Comment by xxmbaobao** [comment]
@nshmura so it is,thanks !

**Comment by nshmura** [comment]
@xxmbaobao Thank you very much for your suggestions!

**Pull request closed without merging**
